# Generated by Django 2.0 on 2018-01-03 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddressBook', '0006_auto_20180103_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message="Zip code must be entered in the format: '666666'. Exactly 6 digits allowed.", regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Exactly 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
