# Generated by Django 2.0 on 2018-02-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddressBook', '0010_auto_20180108_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
